version: '2.1'

volumes:
  nginx-certificates:
  nginx-virtual_hosts:
  nginx-html:
  mysql:

networks:
  docker-postfix-bridge:
    external: true
  web-proxy:
    driver: bridge
  database:
    driver: bridge

services:
  db:
    networks:
      - database
    image: mysql
    # .env-mysql defines `MYSQL_ROOT_PASSWORD`
    env_file: .env-mysql
    volumes:
      - mysql:/var/lib/mysql

  nginx-proxy:
    networks:
      - web-proxy
    ports:
      - 80:80
      - 443:443
    image: jwilder/nginx-proxy
    volumes:
      - /var/cache/nginx:/var/cache/nginx:z
      - ./my-proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - nginx-certificates:/etc/nginx/certs:ro
      - nginx-virtual_hosts:/etc/nginx/vhost.d:Z
      - nginx-html:/usr/share/nginx/html:Z
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./passwords:/etc/nginx/htpasswd:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    security_opt:
      - label:type:docker_t

  nginx-proxy-companion:
    networks:
      - web-proxy
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - nginx-certificates:/etc/nginx/certs:Z
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - label:type:docker_t

  wiki:
    networks:
      - web-proxy
      - database
      - docker-postfix-bridge
    image: cgal/mediawiki:latest
    build: .
    links:
      - db:mysql
    env_file:
      - .env-mysql
      - .env-htpasswd
    environment:
      - VIRTUAL_HOST=localhost
      - MEDIAWIKI_DB_HOST=mysql
      - MEDIAWIKI_DB_NAME=cgalwikidb
    volumes:
      - ${CGAL_WIKI_IMAGES:-./images}:/var/www/html/images:Z
